version: '3.1'

networks:
  bdd:

volumes:
  dbdata:
  grafanadata:

services:
  db: 
    image: "mysql:8.0"
    container_name: "DC_MySQL_PT"
    restart: "always"
    volumes:
    - "dbdata:/var/lib/mysql"
    - "./mysql/script:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: 4IRC
    networks:
    - bdd

  grafana: 
    image: "grafana/grafana:7.4.3"
    container_name: "DC_Grafana_PT"
    restart: "always"
    volumes:
    - "grafanadata:/var/lib/grafana"
    ports:
    - "10502:3000"
    networks:
    - bdd

  phpmyadmin:
    image: "phpmyadmin:5.1.0"
    container_name: "DC_PhpMyAdmin_PT"
    restart: "always"
    environment:
    - "PMA_ARBITRARY=1"
    ports:
    - "10500:80"
    networks:
    - bdd
  
  api:
    build:
      context: "./python/"
      dockerfile: api.DockerFile
    image: "api_pt"
    container_name: "DC_Api_PT"
    restart: "always"
    ports:
    - "10501:80"
    networks:
    - bdd
    depends_on:
    - "db"

  iot:
    build:
      context: "./python/"
      dockerfile: iot.DockerFile
    image: "iot_pt"
    container_name: "DC_Iot_PT"
    restart: "always"
    networks:
    - bdd
    depends_on:
    - "api"
  
  simulateur:
    build:
      context: "./java/"
      dockerfile: simu.DockerFile
    image: "simulateur_pt"
    container_name: "DC_Simulateur_PT"
    restart: "always"
    networks:
    - bdd
    depends_on:
    - "db"
  
  emergency:
    build:
      context: "./java/"
      dockerfile: emergency.DockerFile
    image: "emergency_pt"
    container_name: "DC_Emergency_PT"
    restart: "always"
    networks:
    - bdd
    depends_on:
    - "db"
  
  httpd:
    build:
      context: "./webview/"
      dockerfile: DockerFile
    image: "emergency-view_pt"
    container_name: "DC_View_Emergency_PT"
    restart: "always"
    ports:
    - "80:80"
    networks: 
    - bdd
  
