{
 "title": "Simulation",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Capteur",
   "type": "table",
   "gridPos": { "h": 31, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT idSensor AS \"Capteur ID\", nameStatus AS \"Status\", coordX AS \"Coordonnée X\", coordY AS \"Coordonnée Y\", intensity AS \"Intensité\"\nFROM Sensor\nINNER JOIN Status ON Sensor.statusSensor = Status.idStatus\nORDER BY nameStatus, idSensor ASC"
    }
   ]
  },
  {
   "title": "Casernes",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT FireStation.idFireStation AS \"Casernes ID\", FireStation.nameFireStation AS \"Nom\", FireStation.coordX AS \"Coordonnée X\", FireStation.coordY AS \"Coordonnée Y\", count(Truck.idTruck) AS \"Camions disponibles\"\nFROM FireStation\nINNER JOIN Truck\nON FireStation.idFireStation = Truck.idFireStation\nINNER JOIN Statement\nON Truck.statement = Statement.idStatement\nWHERE Statement.nameStatement = \"ATHOME\"\nGROUP BY FireStation.idFireStation"
    }
   ]
  },
  {
   "title": "Feux en cours",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT count(*)\nFROM Fire" }
   ]
  },
  {
   "title": "Pompier",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT FireStation.idFireStation AS \"Casernes ID\", Fireman.idFireman AS \"Pompier ID\", name AS \"Prenom\", surname AS \"Nom\", Statement.nameStatement AS \"Status\"\nFROM Fireman\nINNER JOIN Truck\nON Fireman.idTruck = Truck.idTruck\nINNER JOIN Statement\nON Truck.statement = Statement.idStatement\nINNER JOIN FireStation\nON Truck.idFireStation = FireStation.idFireStation"
    }
   ]
  }
 ]
}